### ISSUE TITLE
Latest Commit Introduces Breaking Changes

### ISSUE THREAD

**Issue by daleknauss** [MirServer/mir-kiosk-snap-launch#8]
Hello, the commit 9b971771be84ff0a57a4db141e80589d2a2b98dd  made today introduced breaking changes with the core20 base.

Here's what I see in the logs:
```
<my snap>[9525]: + snapctl get daemon
<my snap>[9525]: + [  = true ]
<my snap>[9525]: + snapctl stop <my snap>.daemon
<my snap>[9525]: error: error running snapctl: unknown service: "<my snap>.daemon"
```

I run the snap from a script like: `exec $SNAP/bin/run-daemon wayland-launch $SNAP/my-snap`

Is there a way to pin the `mir-kiosk-snap-launch` part to a previous commit?

**Comment by daleknauss** [comment]
Looks like just removing run-daemon and only using wayland-launch did the trick.

**Comment by AlanGriffiths** [comment]
I'm glad you solved your problem but the real cause was the `daemon` snap setting wasn't set. As both the `install` and `post-refresh` hooks set it it isn't clear how that happened.

To answer your original question: you can specify a commit, tag, or branch.

**Comment by daleknauss** [comment]
@AlanGriffiths than you for your response. I had tried updating to the following configuration (irrelevant plugs and environment keys removed) and it still wasn't working:

```
ui:
    command: ui.sh
    daemon: simple
    restart-condition: always
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
```

and in parts:
```
  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl pulseaudio wayland
    stage-packages:
      - inotify-tools
```

Would you mind telling me how I specify the exact commit in my part?
